### ISSUE TITLE
env: coffee: No such file or directory

### ISSUE THREAD

**Issue by anvk** [Meettya/image-batch-resizer#7]
Everytime I run your code I get:

```
myFolder$ image-batch-resizer -d ./wide.copy
env: coffee: No such file or directory
```

wonder what is the problem

**Comment by Meettya** [comment]
Hi!
Thats my fail, as quick workaround install global coffeescript

`npm install coffee-script -g`

Later I re-build it to ES2015 -> ES5 in bin.

**Comment by Meettya** [comment]
TODO: rewrite to ES5 in bin.

**Comment by Meettya** [comment]
Done
