### ISSUE TITLE
'coffee' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by azarus** [Meettya/image-batch-resizer#9]
Found this lib in google 2 position, but worthless to mention that your lib simply doesnt work. 
```

image-batch-resizer -d images/ -s 1280x720> -p img_
'coffee' is not recognized as an internal or external command,
operable program or batch file.
```

My recommendation for a quick fix would be to this issue is that to simply get rid of coffe script since its not javascript and has no place in npm?

**Comment by Meettya** [comment]
> Dura lex, sed lex
Agreed, will be fixed soon :)

**Comment by Meettya** [comment]
Done, will be updated at npm soon.
